stiffness:
  right_arm:
    - 0.15
    - 0.15
    - 0.15
    - 0.20
    - 0.20
    - 0.20
    - 0.20
  left_arm:
    - 0.15
    - 0.15
    - 0.15
    - 0.20
    - 0.20
    - 0.20
    - 0.20
  torso:
    - 0.0
    - 0.0
    - 0.0
delta_thresh:
  right_arm:
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
  left_arm:
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
  torso:
    - 5.0
    - .25
    - .25
slew_rate: 10.0 #deg/s
