right_arm_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - m3joint_ma10_j0
    - m3joint_ma10_j1
    - m3joint_ma10_j2
    - m3joint_ma10_j3
    - m3joint_ma10_j4
    - m3joint_ma10_j5
    - m3joint_ma10_j6
  gains:
    m3joint_ma10_j0: {p: 240.0, d: 1.0}
    m3joint_ma10_j1: {p: 120.0, d: 1.0}
    m3joint_ma10_j2: {p: 100.0, d: 0.6}
    m3joint_ma10_j3: {p: 70.0, d: 0.4}
    m3joint_ma10_j4: {p: 30.0, d: 0.6}
    m3joint_ma10_j5: {p: 30.0, d: 0.4}
    m3joint_ma10_j6: {p: 30.0, d: 0.4}
#    m3joint_ma10_j0: {p: 50.0, d: 3.0}
#    m3joint_ma10_j1: {p: 50.0, d: 3.0}
#    m3joint_ma10_j2: {p: 50.0, d: 3.0}
#    m3joint_ma10_j3: {p: 50.0, d: 3.0}
#    m3joint_ma10_j4: {p: 10.0, d: 1.0}
#    m3joint_ma10_j5: {p: 10.0, d: 1.0}
#    m3joint_ma10_j6: {p: 10.0, d: 1.0}
  joint_trajectory_action_node:
    joints:
      - m3joint_ma10_j0
      - m3joint_ma10_j1
      - m3joint_ma10_j2
      - m3joint_ma10_j3
      - m3joint_ma10_j4
      - m3joint_ma10_j5
      - m3joint_ma10_j6
    constraints:
      goal_time: 0.6
      m3joint_ma10_j0:
        goal: 0.02
      m3joint_ma10_j1:
        goal: 0.02
      m3joint_ma10_j2:
        goal: 0.02
      m3joint_ma10_j3:
        goal: 0.02
      m3joint_ma10_j4:
        goal: 0.02
      m3joint_ma10_j5:
        goal: 0.02
      m3joint_ma10_j6:
        goal: 0.02
