m3joint_ma10_j0_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j0
  pid: &m3joint_ma10_j0_position_gains
#    p: 300.0
    p: 240.0
    d: 10.0
#    i: 80.0
    i: 0.0
    i_clamp: 0.4
m3joint_ma10_j1_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j1
  pid: &m3joint_ma10_j1_position_gains
    p: 120.0
    d: 5.0
#    i: 70.0
    i: 0.0
    i_clamp: 0.4
m3joint_ma10_j2_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j2
  pid: &m3joint_ma10_j2_position_gains
    p: 100.0
    d: 4.0
#    i: 60.0
    i: 0.0
    i_clamp: 0.4
m3joint_ma10_j3_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j3
  pid: &m3joint_ma10_j3_position_gains
    p: 40.0
    d: 1.0
#    i: 45.0
    i: 0.0
    i_clamp: 0.4
m3joint_ma10_j4_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j4
  pid: &m3joint_ma10_j4_position_gains
    p: 30.0
    d: 3.0
#    i: 30.0
    i: 0.0
    i_clamp: 0.2
m3joint_ma10_j5_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j5
  pid: &m3joint_ma10_j5_position_gains
    p: 30.0
    d: 0.4
    i: 0.0
#    i: 30.0
    i_clamp: 0.2
m3joint_ma10_j6_position_controller:
  type: robot_mechanism_controllers/JointPositionController
  joint: m3joint_ma10_j6
  pid: &m3joint_ma10_j6_position_gains
    p: 30.0
    d: 0.4
#    i: 30.0
    i: 0.0
    i_clamp: 0.2
