language: cpp

compiler:
  - gcc


## Google drive not working on large files-> need shared folder id and complete file name
#  - FILE_ID_HEADERS=0B6zWJ1Gzg1UTZTdVNkJWZG9QSk0
#  - FILE_ID_IMAGE=0B6zWJ1Gzg1UTUWRKQldMZEZnWHc
#  - wget --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILE_ID_HEADERS" -O linux-headers.deb
#  - wget --no-check-certificate "https://docs.google.com/uc?export=download&id=$FILE_ID_IMAGE" -O linux-image.deb

before_install:
  - CI_SOURCE_PATH=$(pwd)
## Parameters
  - rtai_version=4.0
  - kernel_name=3.10.32-rtai4.0_3.10.32-rtai4.0-10.00.Custom_amd64
  - headers=linux-headers-$kernel_name.deb
  - image=linux-image-$kernel_name.deb
  - FOLDER_ID=0B6zWJ1Gzg1UTZWRnQ2lUYjVtWnM
  - linuxx64patch=0B6zWJ1Gzg1UTblBtVGJWZ200eDQ
## Prerequisites
#=======  RT Kernel ========#
  - cd
  - wget https://googledrive.com/host/$FOLDER_ID/$headers
  - wget https://googledrive.com/host/$FOLDER_ID/$image
  - sudo dpkg -i --force-all $headers $image
  - rtkernel=$(dpkg-deb --info $headers |grep Package -m 1 | grep -Po "linux-headers-\K(.*)")
  - wget --no-check-certificate "https://docs.google.com/uc?export=download&id=$linuxx64patch" -O ~/linux-x64.patch
  - cd /usr/src/linux-headers-$rtkernel/arch/x86
  - sudo patch < ~/linux-x64.patch
#=======  RTAI ========#
  - cd
  - sudo apt-get install -qq cvs
  - cvs -d:pserver:anonymous@cvs.gna.org:/cvs/rtai co rtai
#  - wget --no-check-certificate https://www.rtai.org/userfiles/downloads/RTAI/rtai-$rtai_version.tar.bz2
#  - tar xjf rtai-$rtai_version.tar.bz2
#  - ln -snf rtai-$rtai_version rtai 
  - cd rtai && mkdir build && cd build
  - ../configure --disable-comedi-lxrt --with-linux-dir=/usr/src/linux-headers-$rtkernel
  - make -j$(nproc)
  - sudo make install
  - sudo apt-get install -qq swig moc cmake libeigen3-dev libprotobuf-dev protobuf-compiler libboost-dev python-dev python-protobuf python-matplotlib python-yaml python-gnuplot python-scipy python-sip-dev python-sip
#=======  (OPTIONAL) YamlCpp 0.5 ========#
  - cd
  - wget http://yaml-cpp.googlecode.com/files/yaml-cpp-0.5.1.tar.gz
  - tar -xf yaml-cpp-0.5.1.tar.gz
  - cd yaml-cpp-0.5.1
  - mkdir build;cd build;
  - cmake .. -DBUILD_SHARED_LIBS=1
  - make -j$(nproc)
  - sudo make install

 
install:
  - cd $CI_SOURCE_PATH
  - git submodule init && git submodule update
  - git foreach git pull origin master
  - mkdir build
  - cd build
  - cmake -DKERNEL_NAME=$rtkernel ..
  
script:
  - make -j$(nproc)
  - sudo make install
