
########### M3 CONFIG ######################
factory_rt_libs:
  - /usr/local/lib/libm3toolbox.so
  - /usr/local/lib/libm3hardware.so
  - /usr/local/lib/libm3chains.so
  - /usr/local/lib/libm3robots.so
#  - /usr/local/lib/libm3iir.so

factory_py_libs:
  - /usr/local/lib/python2.6/dist-packages/m3/m3meka_factory_proxy.py

hostname: meka-muppet
sys_test: iir
rt_components:
  sys:
    m3monitor_m0: m3monitor
  pwr:
    m3pwr_pwr017: m3pwr
  mh5:
    m3actuator_mh5_j0: m3actuator
    m3actuator_mh5_j1: m3actuator
    m3actuator_mh5_j2: m3actuator
    m3actuator_mh5_j3: m3actuator
    m3actuator_mh5_j4: m3actuator
    m3joint_mh5_j0: m3joint
    m3joint_mh5_j1: m3joint
    m3joint_mh5_j2: m3joint
    m3joint_mh5_j3: m3joint
    m3joint_mh5_j4: m3joint
    m3hand_mh5: m3hand
ec_components:
  pwr:
    m3pwr_ec_pwr017: m3pwr_ec
  mh5:
    m3actuator_ec_mh5_j0: m3actuator_ec
    m3actuator_ec_mh5_j1: m3actuator_ec
    m3actuator_ec_mh5_j2: m3actuator_ec
    m3actuator_ec_mh5_j3: m3actuator_ec
    m3actuator_ec_mh5_j4: m3actuator_ec
