#katana_joints:
meka_joints:
  - m3joint_ma10_j0
  - m3joint_ma10_j1
  - m3joint_ma10_j2
  - m3joint_ma10_j3
  - m3joint_ma10_j4
  - m3joint_ma10_j5
  - m3joint_ma10_j6
#katana_gripper_joints:
#  - katana_r_finger_joint
#  - katana_l_finger_joint
