stiffness:
  right_arm:
    - 0.15
    - 0.15
    - 0.15
    - 0.20
    - 0.20
    - 0.20
    - 0.20
delta_thresh:
  right_arm:
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
    - 5.0
slew_rate: 10.0 #deg/s
