stiffness:
  right_arm:
    - 0.20
    - 0.20
    - 0.10
    - 0.10
    - 0.10
    - 0.10
    - 0.10
delta_thresh:
  right_arm:
    - 5.0
    - 5.0
    - 5.0
    - 10.0
    - 5.0
    - 5.0
    - 5.0
slew_rate: 10.0 #deg/s
