stiffness:
  right_arm:
    - 0.20
    - 0.20
    - 0.10
    - 0.10
    - 0.10
    - 0.10
    - 0.10
  left_arm:
    - 0.20
    - 0.30
    - 0.10
    - 0.15
    - 0.10
    - 0.10
    - 0.10
  torso:
    - 0.0
    - 0.20
    - 0.20
delta_thresh:
  right_arm:
    - 5.0
    - 5.0
    - 5.0
    - 10.0
    - 5.0
    - 5.0
    - 5.0
  left_arm:
    - 5.0
    - 8.0
    - 5.0
    - 10.0
    - 5.0
    - 5.0
    - 5.0
  torso:
    - 5.0
    - 5.0
    - 5.0
slew_rate: 10.0 #deg/s
